name: publish
on: [push]
jobs:
  optimize-android-alpine-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout github repo (+ download lfs dependencies)
      uses: actions/checkout@v2
    - name: Generate Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
        flavor: |
          latest=true
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      id: docker_build
      env:
        DOCKER_BUILDKIT: 1
      with:
        load: false
        push: true
        tags: ${{ steps.meta.outputs.tags }}
  #     cache-from: type=local,src=/tmp/.buildx-cache
  #     cache-to: type=local,dest=/tmp/.buildx-cache-new
  #     labels: ${{ steps.meta.outputs.labels }}
  #     outputs: type=docker,dest=/tmp/myimage.tar
  # - name: Remove cache
  #   run: |
  #     rm -rf /tmp/.buildx-cache-new /tmp/.buildx-cache
  # - name: Squash all docker layers
  #   uses: FallenAngel97/squash-docker@v2.0
  #   with:
  #     tags: ${{ steps.meta.outputs.tags }}
  #   id: squash-step
